version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: RegistroCivilFrontSSL
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./ssl/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      # Si quieres actualizar certificados sin reconstruir, usar vol√∫menes es ideal
    restart: unless-stopped
