services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Pantera_SSL
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl/point.cert:/etc/ssl/point.cert:ro
      - ./ssl/server.key:/etc/ssl/server.key:ro
    restart: unless-stopped
