

version: '3.8'

services:
  react-app:
    build: .
    container_name: RegistroCivilFrontSSL
    ports:
      - "80:80"    # HTTP (redirige a HTTPS)
      - "443:443"  # HTTPS
    restart: unless-stopped
