services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Pantera_SSL
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./ssl/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    restart: unless-stopped
